name: My Action

on:
  workflow_dispatch:
    inputs:
      first_name:
        description: 'First name'
        required: true
      second_name:
        description: 'Second name'
        required: true

jobs:
  my-action-job:
    runs-on: ubuntu-latest

    steps:
      - name: Echo Input Parameters
        run: |
          echo "First name: ${{ github.event.inputs.first_name }}"
          echo "Second name: ${{ github.event.inputs.second_name }}"
