name: Trigger My Global Action

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name'
        required: true

jobs:
  trigger-action-job:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger My Global Action
        uses: your-username/my-global-action@main
        with:
          branch: ${{ github.event.inputs.branch }}
