name: My Other Action

on:
  push:
    branches:
      - main

jobs:
  my-other-action-job:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger My Action
        uses: ./.github/workflows/my-action1.yml  # Replace with the actual path to "My Action" workflow file
        with:
          branch: 'main'  # Replace with the appropriate branch name
          first_name: 'Afaq'
          second_name: 'Nasir'
