name: My Other Action

on:
  push:
    branches:
      - main

jobs:
  my-other-action-job:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger My Action
        uses: ./.github/workflows/InputParameterValues.yml  # Replace with the actual path to "My Action" workflow file
        with:
          first_name: 'Afaq'
          second_name: 'Nasir'
