name: My Other Action

on:
  push:
    branches:
      - main

jobs:
  my-other-action-job:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger My Action
        uses: actions/github-script@v5
        with:
          script: |
            const response = await octokit.request('POST /repos/AfaqNasir/Trigger-My-Global-Action/actions/workflows/5475844018/dispatches', {
              owner: 'AfaqNasir',
              repo: 'Trigger-My-Global-Action',
              workflow_id: '.github/workflows/InputParameterValues.yml',  // Replace with the actual workflow file path of "My Action"
              ref: 'main',  // Replace with the branch of "My Action"
              inputs: {
                first_name: 'Afaq',
                second_name: 'Nasir'
              }
            });
            console.log(response.data);
